# Generated by Django 4.2.3 on 2023-07-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='height',
            field=models.CharField(max_length=100),
        ),
    ]
