# Generated by Django 4.2.3 on 2023-07-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0002_alter_book_height'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='author_database',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='height',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='author_storage',
            field=models.CharField(default='anonymous', max_length=150),
        ),
        migrations.AddField(
            model_name='book',
            name='genre_database',
            field=models.CharField(default='anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='genre_storage',
            field=models.CharField(default='anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='height_database',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='book',
            name='height_storage',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_database',
            field=models.CharField(default='anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_storage',
            field=models.CharField(default='anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='title_database',
            field=models.CharField(default='anonymous', max_length=150),
        ),
        migrations.AddField(
            model_name='book',
            name='title_storage',
            field=models.CharField(default='anonymous', max_length=150),
        ),
    ]
