# Generated by Django 4.2.3 on 2023-07-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0004_remove_book_author_storage_remove_book_genre_storage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_database',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='genre_database',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publisher_database',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title_database',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='height_database',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='anonymous', max_length=100),
        ),
    ]
